package main

//proposed solution to https://projecteuler.net/problem=2
import "fmt"

var total int

func main() {
	for i, j := 0, 1; j < 4000000; i, j = i+j, i {
		//	fmt.Println(i)
		if i%2 == 0 {
			total = total + i
		}
	}
	fmt.Println(total)
}

//description of problem:
//Each new term in the Fibonacci sequence is generated by adding the previous two terms.
//By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million,
//find the sum of the even-valued terms.

//note from the student:
//so I got completely stuck on how to initialize the fibonacci sequence
//**full disclosure: I got the fibonacci sequence in go from a web search
//and then I put the conditional statement in to get the answer
